#!/usr/bin/env bash
# Compiles both circuits, writes their verification keys and Solidity
# verifiers, and publishes the artifacts the web app loads.
#
#   circuits/target/<name>.json              compiled circuit
#   circuits/target/vk/<name>/vk             verification key (evm target)
#   contracts/src/verifiers/<Name>Verifier.sol
#   web/public/circuits/<name>.<hash>.json   content-addressed, for the prover
#
# Re-run it after any change to circuits/ and commit what it produces.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$root/circuits"

nargo_version="$(nargo --version | head -1 | sed 's/nargo version = //')"
bb_version="$(bb --version)"
echo "nargo $nargo_version · bb $bb_version"

nargo compile

mkdir -p "$root/contracts/src/verifiers" "${ARTIFACTS_DIR:-$root/web/public/circuits}"
manifest="$root/web/public/circuits/manifest.json"
echo "{" > "$manifest.tmp"

first=1
for circuit in spend settle; do
  name="$(echo "${circuit:0:1}" | tr '[:lower:]' '[:upper:]')${circuit:1}"

  bb write_vk --scheme ultra_honk --verifier_target evm \
    -b "target/$circuit.json" -o "target/vk/$circuit" >/dev/null
  bb write_solidity_verifier --scheme ultra_honk \
    -k "target/vk/$circuit/vk" -o "target/vk/$circuit/Verifier.sol" >/dev/null

  out="$root/contracts/src/verifiers/${name}Verifier.sol"
  {
    echo "// Generated by circuits/scripts/build.sh. Do not edit."
    echo "// circuit: $circuit · nargo $nargo_version · bb $bb_version"
    echo "// vk hash: $(xxd -p -c 64 "target/vk/$circuit/vk_hash")"
    sed "s/^contract HonkVerifier is/contract ${name}Verifier is/" "target/vk/$circuit/Verifier.sol"
  } > "$out"

  # The prover needs the ABI and bytecode only. Debug symbols carry absolute
  # source paths from the build machine, so they stay out of the site.
  python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); [d.pop(k,None) for k in ("debug_symbols","file_map")]; json.dump(d,open(sys.argv[2],"w"),separators=(",",":"))' \
    "target/$circuit.json" "target/$circuit.public.json"
  hash="$(shasum -a 256 "target/$circuit.public.json" | cut -c1-12)"
  cp "target/$circuit.public.json" "$root/web/public/circuits/$circuit.$hash.json"
  # Drop stale copies of the same circuit.
  find "${ARTIFACTS_DIR:-$root/web/public/circuits}" -name "$circuit.*.json" ! -name "$circuit.$hash.json" -delete

  [ $first -eq 0 ] && echo "," >> "$manifest.tmp"
  first=0
  printf '  "%s": { "file": "%s.%s.json", "hash": "%s" }' "$circuit" "$circuit" "$hash" "$hash" >> "$manifest.tmp"
  echo "  $circuit → $name Verifier, artifact $circuit.$hash.json"
done

{ echo ""; echo "}"; } >> "$manifest.tmp"
mv "$manifest.tmp" "$manifest"

cat > "$root/circuits/versions.json" <<EOF
{
  "nargo": "$nargo_version",
  "bb": "$bb_version",
  "verifierTarget": "evm",
  "scheme": "ultra_honk"
}
EOF
echo "done"
